### ISSUE TITLE
Docker setup failed

### ISSUE THREAD

**Issue by shyshywhy** [github/libprojfs#81]
when run ./projfs setup: 
```
Step 4/4 : RUN chmod 0777 /data
 ---> Using cache
 ---> 52384ab289d6
Successfully built 52384ab289d6
Successfully tagged github/vfs-linux:latest
>> docker run -u 1001 --pid=host --rm --name projfs-vfs -v /data00/home/tanhaiyang/libprojfs/docker/VFSForGit:/data/vfs/src -v /data00/home/tanhaiyang/libprojfs/docker/build/packages:/data/vfs/packages -v /data00/home/tanhaiyang/libprojfs/docker/build/BuildOutput:/data/vfs/BuildOutput github/vfs-linux env DOTNET_CLI_TELEMETRY_OPTOUT=1 DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1 NUGET_XMLDOC_MODE=skip dotnet restore MirrorProvider/MirrorProvider.sln /p:Configuration=Debug.Linux --packages ../packages
MSBUILD : error MSB1009: Project file does not exist.
Switch: MirrorProvider/MirrorProvider.sln
./projfs:95:in `system': failed to run 'docker run -u 1001 --pid=host --rm --name projfs-vfs -v /data00/home/tanhaiyang/libprojfs/docker/VFSForGit:/data/vfs/src -v /data00/home/tanhaiyang/libprojfs/docker/build/packages:/data/vfs/packages -v /data00/home/tanhaiyang/libprojfs/docker/build/BuildOutput:/data/vfs/BuildOutput github/vfs-linux env DOTNET_CLI_TELEMETRY_OPTOUT=1 DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1 NUGET_XMLDOC_MODE=skip dotnet restore MirrorProvider/MirrorProvider.sln /p:Configuration=Debug.Linux --packages ../packages (RuntimeError)
	from /data00/home/tanhaiyang/libprojfs/docker/project.rb:71:in `run'
	from /data00/home/tanhaiyang/libprojfs/docker/project.rb:50:in `block in command'
	from /data00/home/tanhaiyang/libprojfs/docker/project.rb:49:in `each'
	from /data00/home/tanhaiyang/libprojfs/docker/project.rb:49:in `command'
	from ./projfs:206:in `<main>'
tanhaiyang@n227-087-045:~/libprojfs/docker$ docker run -u 1001 --pid=host --rm --name projfs-vfs -v /data00/home/tanhaiyang/libprojfs/docker/VFSForGit:/data/vfs/src -v /data00/home/tanhaiyang/libprojfs/docker/build/packages:/data/vfs/packages -v /data00/home/tanhaiyang/libprojfs/docker/build/BuildOutput:/data/vfs/BuildOutput github/vfs-linux env DOTNET_CLI_TELEMETRY_OPTOUT=1 DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1 NUGET_XMLDOC_MODE=skip dotnet restore MirrorProvider/MirrorProvider.sln /p:Configuration=Debug.Linux --packages ../packages
MSBUILD : error MSB1009: Project file does not exist.
Switch: MirrorProvider/MirrorProvider.sln 
```

**Comment by shyshywhy** [comment]
@chrisd8088 @kivikakk
